### ISSUE TITLE
How are external references supposed to be treated?

### ISSUE THREAD

**Issue by olydis** [Mermade/swagger2openapi#10]
When running `convertFile` over (a local clone of) https://github.com/Azure/azure-rest-api-specs/blob/master/arm-apimanagement/2016-10-10/swagger/apimnetworkstatus.json#L49, I get
> Error: Could not resolve reference ./apimanagement.json#/parameters/SubscriptionIdParameter

Ideally (from our perspective 😄) those references would be converted *blindly*, i.e. without touching the external file, but converting the `#/...` part *assuming* that the external file undergoes the same conversion.

I see things like `common.resolveExternal` if `resolve` is activated (which throws another Error for me), but also that looks as if it would touch the external file. I'd love to contribute, but wanted to hear your side of the story, maybe there is already something in place I'm unaware of. 🙂

**Comment by MikeRalphson** [comment]
Apologies for the delay, I've been at a music festival all week. There are undoubtedly holes in both the resolution logic and coverage of the use-case you mention.

I will get an option added (once I think of a good name for it) - thanks for the detailed issue.

**Comment by olydis** [comment]
Hehe no worries, hope it was fun. 😃 Thanks!

**Comment by MikeRalphson** [comment]
Working on this now - your use-case will now be the default behaviour, but just to clarify:

> I see things like common.resolveExternal if resolve is activated (which throws another Error for me), but that looks as if it would touch the external file

If you had a local clone of the included files too (or you converted from a URL source), there should be no error, but the relevant part of the external file would be included (and converted).

**Comment by MikeRalphson** [comment]
Should be fixed in v2.5.0

**Comment by olydis** [comment]
Awesome, thanks!
