### ISSUE TITLE
Numbers are unsupported

### ISSUE THREAD

**Issue by Alan-Cha** [Mermade/swagger2openapi#11]
Hello! We are trying to build an application that uses your library. Unfortunately, there seems to be something wrong... We encounter a problem when we try to validate our test OAS which utilizes numbers, specifically in the server object definition. It seems that your validator does not like numbers in the OAS.  

Here is our error:
```
AssertionError: expected 3000 to have type string
      expected 'number' to be 'string'
      
      at Assertion.fail (node_modules/should/cjs/should.js:258:17)
      at Assertion.value [as type] (node_modules/should/cjs/should.js:335:19)
      at checkServers (node_modules/swagger2openapi/validate.js:119:43)
      at Object.validateSync (node_modules/swagger2openapi/validate.js:349:3)
```

And here is our server object definition, note the default port number:
```
{
  "servers": [
    {
      "url": "http://localhost:{port}/{basePath}",
      "description": "The location of the local test server.",
      "variables": {
        "port": {
          "default": 3000
        },
        "basePath": {
          "default": "api"
        }
      }
    }
  ]
}
```

We thought that we were following proper OAS specification as the official specification page has a very similar [example](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#server-object-example) which can be seen here:
```
{
  "servers": [
    {
      "url": "https://{username}.gigantic-server.com:{port}/{basePath}",
      "description": "The production API server",
      "variables": {
        "username": {
          "default": "demo",
          "description": "this value is assigned by the service provider, in this example `gigantic-server.com`"
        },
        "port": {
          "enum": [
            8443,
            443
          ],
          "default": 8443
        },
        "basePath": {
          "default": "v2"
        }
      }
    }
  ]
}
```

**Comment by MikeRalphson** [comment]
Hi @Alan-Cha this isn't a generic problem with numbers in the validator.

Both the server variable  `default` and `enum` properties can only contain strings (the `enum` being an array of strings).

See [here](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#fixed-fields-5) in the specification.

In this case, it is the example which is wrong.

**Comment by MikeRalphson** [comment]
I've raised a PR to correct the example in the specification: https://github.com/OAI/OpenAPI-Specification/pull/1251

**Comment by MikeRalphson** [comment]
https://github.com/OAI/OpenAPI-Specification/pull/1251 has been merged.
