### ISSUE TITLE
SecuritySchemes: JWT tokens not valid

### ISSUE THREAD

**Issue by pjmolina** [Mermade/swagger2openapi#2]
Hi Mike:

Validating a contract with something like this:

```json
{
  "components": {
    "securitySchemes": {
      "autentication_jwt": {
        "type": "scheme",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
	...
```

Got this error:
```json
{
  "status": false,
  "message": "expected Object { type: 'scheme', scheme: 'bearer', bearerFormat: 'JWT' } not to have property scheme (false negative fail)",
  "context": "#/components/securitySchemes/autentication_jwt"
}
```

Accordingly the Spec, this is a sample with the [same info](https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#jwt-bearer-sample). This should be valid, isn't it?

Repro [sample](https://gist.githubusercontent.com/pjmolina/c1aa101d97e5e955920a26d6b7ba1792/raw/ed8daf143c83ba78e3d4457a884138bb8842c708/Sample-OpenAPIv3-Spec.json).

**Comment by MikeRalphson** [comment]
@pjmolina Hi - in this case I think the JSON example snippet is wrong. According to the fixed fields section above that example the only valid `type`s are `http, apiKey, oauth2, openIdConnect`, as per the yaml example.

If you agree, one of us should raise a PR on the v3 spec to fix the example.

**Comment by pjmolina** [comment]
I see. Feel free and go for it!

**Comment by MikeRalphson** [comment]
I've improved the error message to make the problem clearer

>#/components/securitySchemes/jwt
expected 'scheme' to be equals one of Array [ 'apiKey', 'http', 'oauth2', 'openIdConnect' ]

**Comment by MikeRalphson** [comment]
Thanks for the report.
