### ISSUE TITLE
Online version down (Application error)

### ISSUE THREAD

**Issue by vmavromatis** [Mermade/swagger2openapi#20]
I am trying to access the online Heroku app, yet the website displays an error: 

![image](https://user-images.githubusercontent.com/8668731/30921425-c5cbdccc-a3a6-11e7-8cdb-14144c1fb8f6.png)

Thank you,
Vasilis

**Comment by MikeRalphson** [comment]
Hi @vmavromatis yes, it's been a bit popular this month and we've used our quota on Heroku.

I'm trying to bring up a copy on Google appspot at the moment. Please bear with us.

Thanks for reporting!

**Comment by vmavromatis** [comment]
Keep up the good work, looking forward.

**Comment by MikeRalphson** [comment]
Would you be able to test the backup version at http://openapi-converter.appspot.com/ ?

**Comment by vmavromatis** [comment]
> Would you be able to test the backup version at http://openapi-converter.appspot.com/ ?

Gladly. However I paste my [JSON](https://apps.test.hotelbeds.com/swagger.json) and get redirected to:
http://openapi-converter.appspot.com/api/v1/convert with a page body that prints:
```
{
  "status": true
}
```

**Comment by MikeRalphson** [comment]
If you untick the `validate` box - does that fix it? I should probably ensure that defaults to off...

**Comment by vmavromatis** [comment]
Yes, that was it! Thank you, seems to have worked fine.

**Comment by MikeRalphson** [comment]
Thanks for testing. I'll leave this issue open until the Heroku quota resets on October the 1st.

**Comment by ForsakenHarmony** [comment]
https://openapi-converter.hrmny.pw/

made my own mirror idk why

**Comment by MikeRalphson** [comment]
Thanks!

**Comment by MikeRalphson** [comment]
App is back up again, thanks again for reporting.

**Comment by MikeRalphson** [comment]
Happened again this month

**Comment by vmavromatis** [comment]
@MikeRalphson Not sure if it's any use but you can extend to 1000hrs with a CC 
https://devcenter.heroku.com/articles/free-dyno-hours#usage

**Comment by MikeRalphson** [comment]
@vmavromatis thanks, but I've got a grandfathered account with 1,550 free hours and I'm still running out! I need to move an app elsewhere but still deciding which one and where.

**Comment by vmavromatis** [comment]
@MikeRalphson There's an open-source alternative https://github.com/githubsaturn/captainduckduck which you could setup on your own server or AWS. I haven't tried it but there's a reddit thread about it here: https://www.reddit.com/r/programming/comments/78lwoy/open_source_heroku/

**Comment by ForsakenHarmony** [comment]
my mirror is still up if anyone needs it

**Comment by MikeRalphson** [comment]
Thanks @ForsakenHarmony. Heroku version available again.

**Comment by MikeRalphson** [comment]
References updated to hopefully long-term URL: https://mermade.org.uk/openapi-converter
