### ISSUE TITLE
Swagger 2 without scheme doesn't default to anything and loses `host`

### ISSUE THREAD

**Issue by domharrington** [Mermade/swagger2openapi#46]
### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [ ] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains
- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain

### Detailed Description
A swagger file without a schemes array results in an empty OAS 3 `servers` array.

Consider the following minimal (valid) Swagger 2 file:

```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger 2.0 Without Scheme"
  },
  "host": "example.com",
  "paths": {}
}
```

When converted, this results in the following output:

```json
{
    "openapi": "3.0.0",
    "servers": [],
    "info": {
        "version": "1.0.0",
        "title": "Swagger 2.0 Without Scheme"
    },
    "paths": {}
}
```

Losing any information to do with the host.

When there is a `basePath`, like so:

```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger 2.0 Without Scheme"
  },
  "host": "example.com",
  "basePath": "/api",
  "paths": {}
}
```

It converts to the following:

```json
{
    "openapi": "3.0.0",
    "servers": [
        {
            "url": "/api"
        }
    ],
    "info": {
        "version": "1.0.0",
        "title": "Swagger 2.0 Without Scheme"
    },
    "paths": {}
}
```

Adding a scheme makes it work for both of these cases. Maybe we could create a `scheme`-less server url and output that? 

I had a quick look at the code and couldnt figure out where to add test cases such as the above. Happy to send a PR to fix this if you tell me where in the code to look!

#### Other stuff

We're using it pretty extensively over at https://readme.io/ for some OAS 3 related stuff! We're happy to contribute back.

**Comment by MikeRalphson** [comment]
Thanks for reporting this, and the detailed replication steps.

Tests with expected outputs (rather than just passing the validator) is definitely a lacking area.

The issue should be fixed in v2.11.8, would be grateful if you could confirm.

**Comment by domharrington** [comment]
Excellent! That appears to be fixed. If you'd accept a PR for a simple solution of input/output testing with swagger/oas files, i'd be happy do contribute! Let me know.

**Comment by MikeRalphson** [comment]
> If you'd accept a PR for a simple solution of input/output testing with swagger/oas files, i'd be happy to contribute.

This would be very gratefully received! A framework and an example or two we can build on would be fantastic.
