### ISSUE TITLE
Validator complains when using deprecated property

### ISSUE THREAD

**Issue by pfd** [Mermade/swagger2openapi#49]
### Checklist

- [x] Validation: I believe my source definition is valid OpenAPI 3.0.x but the validator complains

### Detailed Description

Hi there,

We are writing OpenAPI 3.0.0 definitions and recently added this package to our gulp tasks for validation. We're getting the following error when using `deprecated: true` on a property definition. 

```
[16:52:05] Starting 'validate'...
[16:52:05] #/components/schemas/channelObject/properties/alias
Schema object cannot have additionalProperty: deprecated
```

Early on, we had no issues using the Swagger Editor, indeed the HTML output was nicely grayed out so I'd assumed that it was a valid usage (see screen shot).

![screen shot 2018-01-22 at 4 50 19 pm](https://user-images.githubusercontent.com/7563702/35252512-a3fcf180-ff95-11e7-9092-ecfbc541fb4c.png)

#### Other stuff

Thanks for having a look and making such a useful tool!

@pfd

**Comment by MikeRalphson** [comment]
It absolutely is valid usage, the `deprecated` property was accidentally omitted from the list of valid schema object properties. This should be fixed in v2.11.10. Please chase if any further problems, and thank you for the report.
