### ISSUE TITLE
Exit code is zero when parsing fails

### ISSUE THREAD

**Issue by jeffhiltz** [Mermade/swagger2openapi#53]
### Detailed Description

I would like to use swagger2openapi for validation of my OpenAPI 3 yaml files in our build process.  When I run it on an invalid input file I get the expected error message on STDERR, but the exit code is zero.  It would be much easier to detect invalid files if the exit code was non-zero.

```
bash-3.2$ swagger2openapi swagger.yaml
(node:13188) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: (Patchable) info object is mandatory
(node:13188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
bash-3.2$ echo $?
0
```

(Also the actual error message is buried in the UnhandledPromiseRejectionWarning which isn't ideal.  It would be nice to get rid of those unhandled promise warnings.)

#### Other stuff

I found the tool while looking for a good way to convert our Swagger 2.0 files to OpenAPI 3.  The awesome-openapi3 list helped.

Thanks.

**Comment by MikeRalphson** [comment]
Thanks for the report, will take a look at both issues.

**Comment by MikeRalphson** [comment]
Can I check which version you're running?

It looks like that got fixed in commit 72bd25bb - which is included in v2.11.13

```
node swagger2openapi.js test/\!missing-info/swagger.yaml && echo ok
Error: (Patchable) info object is mandatory
    at fixInfo (/home/mike/nodejs/swagger2openapi/index.js:1129:27)
    at /home/mike/nodejs/swagger2openapi/index.js:1313:9
    at new Promise (<anonymous>)
    at convertObj (/home/mike/nodejs/swagger2openapi/index.js:1198:28)
    at /home/mike/nodejs/swagger2openapi/index.js:1376:13
    at new Promise (<anonymous>)
    at convertStr (/home/mike/nodejs/swagger2openapi/index.js:1362:28)
    at /home/mike/nodejs/swagger2openapi/index.js:1415:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

You might get clearer output from using `testRunner -n` in your CI process, and this has the benefit that it actually runs the validator on the converted output:

```
node testRunner.js -v -n swagger.yaml && echo ok
Gathering...
Error: (Patchable) info object is mandatory 

Failures:
Converter failed swagger.yaml

Tests: 0 passing, 1 failing, 0 warnings
```

In both cases above `ok` is not echoed, as the exit code is non-zero.

**Comment by jeffhiltz** [comment]
Fantastic!  All I needed was an update.  :)

I also really appreciate the advice about the testRunner.  And most of all, thank you for the quick response!  I'm about to modify a bunch of services and I'm very, very happy to know this before I start.  🙇

**Comment by MikeRalphson** [comment]
No problem, please let me know if you hit any other issues.
