### ISSUE TITLE
Can swagger2openapi convert from openapi3 to openapi2/swagger2?

### ISSUE THREAD

**Issue by stianlagstad** [Mermade/swagger2openapi#58]
Sorry if this is off-topic. I would like to use [swagger-codegen](https://github.com/swagger-api/swagger-codegen) to create a simple SDK for an API that's documented with openapi3. But since swagger-codegen isn't quite there yet for openapi3, I'm looking for a way to convert our openapi3 spec to openapi2. Is that possible to do with swagger2openapi?

**Comment by stianlagstad** [comment]
I found a converter that might do the trick: [api-spec-converter](https://www.npmjs.com/package/api-spec-converter).
```
➜  api-spec-converter http://doc.cognitedata.com/openapi.json --from=openapi_3 --to=swagger_2 --syntax=yaml > swagger2.yaml
unsupported request body media type tagMatching { '*/*': { schema: { '$ref': '#/components/schemas/TagMatchingInput' } } }
unsupported request body media type postNewModel { '*/*': { schema: { '$ref': '#/components/schemas/3D Model' } } }
unsupported request body media type postNewRevisionJob { '*/*': { schema: { '$ref': '#/components/schemas/File Id Body' } } }
```
I'm going to test it with swagger-codegen and see how it goes.

**Comment by MikeRalphson** [comment]
openapi-codegen uses the same downconverter as api-spec-converter internally, so might also work for you.

**Comment by stianlagstad** [comment]
Thanks Mike!

**Comment by lukekhamilton** [comment]
Hey @stianlagstad, I have been thinking about doing something very similar and would really love to hear about your experience in using a OSA3 to 2 downgrade process and what pros and cons you hit up against? The project I'm working on we are looking at using golang for our api development however the best pkg out there is go-swagger and its only v2 at this point.

Any info would be greatly appreciated. Thanks!

**Comment by stianlagstad** [comment]
@lukekhamilton Not much to tell, I'm afraid. We only did a couple of tests using it and have so far decided against generating our SDK code from specs.
