### ISSUE TITLE
Requiredness of body parameter lost

### ISSUE THREAD

**Issue by olydis** [Mermade/swagger2openapi#6]
## Input
``` JSON
{
  "name": "indexer",
  "in": "body",
  "required": true,
  "schema": {
    "$ref": "#/definitions/Indexer"
  },
  "description": "The definition of the indexer to create or update."
}
```
## Output
``` JSON
"requestBody": {
  "content": {
    "application/json": {
      "description": "The definition of the indexer to create or update.",
      "schema": {
        "$ref": "#/components/schemas/Indexer"
      }
    }
  }
}
```
## Expected
``` JSON
"requestBody": {
  "content": {
    "application/json": {
      "description": "The definition of the indexer to create or update.",
      "schema": {
        "$ref": "#/components/schemas/Indexer"
      }
    }
  },
  "required": true
}
```
## Detail
According to https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#request-body-object, `required` defaults to `false`, so it needs to be set to `true` explicitly 🙂

**Comment by MikeRalphson** [comment]
Thanks for reporting! Am on it.

**Comment by olydis** [comment]
whoops, saw your comment only now, but didn't take much time to fix (in case the fix is okay, haven't spent too much time following the code) 🙂 awesome project!

**Comment by MikeRalphson** [comment]
> whoops, saw your comment only now, but didn't take much time to fix (in case the fix is okay, haven't spent too much time following the code) 🙂 awesome project!

No, @olydis that's cool - the fix is correct and helped me decide which branch to apply it to. (Let me know if you're using the npm package and/or the web front-end and I will do a proper release).

Have applied a similar fix for 2.0 `in: file` parameters.

Thanks again for spotting the issue, and for the PR and kind comments.

**Comment by olydis** [comment]
Sweet, thank *you* for the efforts and super quick response times! I'm consuming the npm package.

**Comment by MikeRalphson** [comment]
> I'm consuming the npm package.

v2.2.1 just published.
